# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "kannkyo/ubuntu-focal64"
  config.vm.box_check_update = true

  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder "share/", "/mnt/host"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.cpus = 1
    vb.memory = 1024
    vb.customize [
      "modifyvm", :id,
      "--vram", "256", # ビデオメモリ確保（フルスクリーンモードにするため
      "--clipboard", "bidirectional", # クリップボードの共有
      "--accelerate3d", "on",
      "--hwvirtex", "on",
      "--nestedpaging", "on",
      "--largepages", "on",
      "--ioapic", "on",
      "--pae", "on",
      "--paravirtprovider", "kvm",
    ]
  end

  config.vm.provision "shell", inline: <<-SHELL
    apt install ubuntu-desktop -y
    locale-gen ja_JP.UTF-8
    echo export LANG=ja_JP.UTF-8 >> ~/.profile
    source ~/.profile
    timedatectl set-timezone Asia/Tokyo
  SHELL
end