# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/contrib-buster64"
  config.vm.box_version = "10.20211018.1"

  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder "../../_share/", "/mnt/host"
  
  config.vm.provider "virtualbox" do |vb|
    vb.name = "debian-contrib-buster64-10.20211018.1"
    vb.gui = false
    vb.cpus = 1
    vb.memory = 1024
  end

  config.vm.network "forwarded_port", guest: 64295, host: 2100, id: "ssh"   # SSH
  config.vm.network "forwarded_port", guest: 64297, host: 2101              # web admin
end
