# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.box_version = "20201117.0.0"

  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder "share/", "/mnt/host"
  
  config.vm.provider "virtualbox" do |vb|
    vb.name = "ubuntu-focal64-20201117.0.0"
    vb.gui = false
    vb.cpus = 1
    vb.memory = 1024
  end
end