# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.box_check_update = true

  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder "../../_share/", "/mnt/host"
  
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.cpus = 1
    vb.memory = 1024
  end

  config.vm.provision "shell", inline: <<-SHELL
    pushd /mnt/host/installer
      bash ubuntu-bionic.sh
    popd
  SHELL
end
