# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/centos6"
  config.vm.box_version = "4.2.6"
  config.vm.box_check_update = false

  # for CentOS8
  # https://github.com/dotless-de/vagrant-vbguest/blob/main/CHANGELOG.md#0240beta1-2020-04-28
  config.vbguest.installer_options = { allow_kernel_upgrade: true }
  config.vm.network "forwarded_port", guest: 22, host: 1234, id: "ssh"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "centos-6"
    vb.gui = false
    vb.cpus = 2
    vb.memory = 2048
  end
end
