# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "kalilinux/rolling"
  config.vm.box_version = "2021.2.0"
  config.vm.box_check_update = false

  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder "../../_share/", "/mnt/host"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "kalilinux-2021.2.0"
    vb.gui = false
    vb.cpus = 1
    vb.memory = 1024
  end
end
